name: lint and tests
on: push
jobs:
  ID: CC_ID
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: make lint
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: npm install jest
      - run: npm install commander
      - run: npm install lodash
      - run: npm test
      - uses: paambaati/codeclimate-action@v3.0.0
        env: 
          CC_TEST_REPORTER_ID: ${{ secrets.CC_ID }}
        with:
          coverageCommand: make test-coverage
          debug: true